export type OrderTab = 'market' | 'limit';
export type OrderSide = 'buy' | 'sell';
export type OrderCurrency = 'USDT' | 'BTC';

export type OrderPanelProps = {
  className?: string;
  activeTab?: OrderTab;
  defaultTab?: OrderTab;
  onTabChange?: (tab: OrderTab) => void;
  side?: OrderSide;
  defaultSide?: OrderSide;
  onSideChange?: (side: OrderSide) => void;
  currency?: OrderCurrency;
  defaultCurrency?: OrderCurrency;
  onCurrencyChange?: (currency: OrderCurrency) => void;
  amount?: string;
  onAmountChange?: (value: string) => void;
  limitPrice?: string;
  onLimitPriceChange?: (value: string) => void;
  stopLossValue?: string;
  onStopLossChange?: (value: string) => void;
  takeProfitValue?: string;
  onTakeProfitChange?: (value: string) => void;
  equity?: string;
  liqPrice?: string;
  max?: string;
  cost?: string;
  margin?: string;
  price?: string;
  onClose?: () => void;
  onPlaceOrder?: () => void;
  onSwapCurrency?: () => void;
};
