import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const coinsDir = path.resolve(root, '../flowx/public/icons/coins');
const outFile = path.resolve(root, 'src/generated/coinCatalog.ts');

const FEATURED_COIN_IDS = ['btc', 'eth', 'sol', 'bnb', 'hype', 'xrp'];

function coinIdToLabel(coinId) {
  return `${coinId.toUpperCase()}USDT`;
}

function coinIdToValue(coinId) {
  return `asset-${coinId}`;
}

const coinIds = fs
  .readdirSync(coinsDir)
  .filter((name) => name.endsWith('.webp'))
  .map((name) => name.slice(0, -'.webp'.length))
  .sort((a, b) => a.localeCompare(b));

const featuredSet = new Set(FEATURED_COIN_IDS);
const orderedCoinIds = [
  ...FEATURED_COIN_IDS.filter((id) => coinIds.includes(id)),
  ...coinIds.filter((id) => !featuredSet.has(id)),
];

const suggestions = orderedCoinIds.map((coinId) => ({
  value: coinIdToValue(coinId),
  label: coinIdToLabel(coinId),
  coinId,
  keywords: [coinId, coinIdToLabel(coinId)],
}));

const file = `/** Generated by scripts/generateCoinCatalog.mjs — do not edit. */
export const COIN_IDS: readonly string[] = ${JSON.stringify(orderedCoinIds)};

export type TerminalAssetSuggestion = {
  value: string;
  label: string;
  coinId: string;
  keywords?: string[];
};

export const TERMINAL_ASSET_SUGGESTIONS: readonly TerminalAssetSuggestion[] = ${JSON.stringify(suggestions)};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, file);
console.log(`Wrote ${orderedCoinIds.length} coins to ${path.relative(root, outFile)}`);
